2025-02-07 11:34:13,357 - INFO - Namespace(device='cuda:1', channel_weights=[1.0, 2.0, 1.0, 1.0], batch_size=2, num_classes=4, pretrained=False, pretrained_weights='./Synapse_weights_1u1d', lr=0.0001, epochs=500, warmup_epochs=10, dataset_mode='ACDC', max_channel=256, l2_norm=1e-07, patience=15, wandb=True, cache=True, ed_es_only='', log_dir='../../de_logistics/ACDC_1UNetlinear_02-07-11-34-12/', log_file_path='../../de_logistics/ACDC_1UNetlinear_02-07-11-34-12/training.log')
2025-02-07 11:34:17,097 - ERROR - Error during DataLoader iteration: [Errno 2] No such file or directory: 'preprocessed_ACDC_sub1/train'
Traceback (most recent call last):
  File "/data2/lyw/deunet_mem_based/train.py", line 40, in main
    train_dataset = cmr_dataset(data_dir=f'preprocessed_ACDC_sub1/train', cache=args.cache)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data2/lyw/deunet_mem_based/utils/cmr_dataset.py", line 12, in __init__
    self.files = [f for f in os.listdir(data_dir) if f.endswith('.h5') and ed_es_only in f]
                             ^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'preprocessed_ACDC_sub1/train'
Traceback (most recent call last):
  File "/data2/lyw/deunet_mem_based/train.py", line 229, in <module>
    main(args, net)
  File "/data2/lyw/deunet_mem_based/train.py", line 70, in main
    train_acc, train_losses = train_epoch(args, net, optimizer, train_loader, device, epoch, scheduler)
                                                                ^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'train_loader' where it is not associated with a value
