2025-02-03 13:50:52,460 - INFO - Namespace(device='cuda:4', channel_weights=[1.0, 2.0, 1.0, 1.0], batch_size=6, num_classes=4, pretrained=False, pretrained_weights='./Synapse_weights_1u1d', lr=0.0001, epochs=500, warmup_epochs=10, dataset_mode='MnMs', max_channel=256, l2_norm=1e-07, patience=15, wandb=True, cache=True, log_dir='../../de_logistics/MnMs_1UNetlinear_02-03-13-50-51/', log_file_path='../../de_logistics/MnMs_1UNetlinear_02-03-13-50-51/training.log')
2025-02-03 13:50:52,560 - ERROR - Error during DataLoader iteration: [Errno 2] No such file or directory: '../../de_data/preprocessed_MnMs/train'
Traceback (most recent call last):
  File "/data2/lyw/deunet_mem_based/train.py", line 39, in main
    train_dataset = cmr_dataset(data_dir=f'../../de_data/preprocessed_{args.dataset_mode}/train', cache=args.cache)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data2/lyw/deunet_mem_based/utils/cmr_dataset.py", line 12, in __init__
    self.files = [f for f in os.listdir(data_dir) if f.endswith('.h5') and ed_es_only in f]
                             ^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '../../de_data/preprocessed_MnMs/train'
Traceback (most recent call last):
  File "/data2/lyw/deunet_mem_based/train.py", line 220, in <module>
    main(args, net)
  File "/data2/lyw/deunet_mem_based/train.py", line 68, in main
    train_acc, train_losses = train_epoch(args, net, optimizer, train_loader, device, epoch, scheduler)
                                                                ^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'train_loader' where it is not associated with a value
