2025-02-03 13:52:30,513 - INFO - Namespace(device='cuda:4', channel_weights=[1.0, 2.0, 1.0, 1.0], batch_size=6, num_classes=4, pretrained=False, pretrained_weights='./Synapse_weights_1u1d', lr=0.0001, epochs=500, warmup_epochs=10, dataset_mode='MnMs', max_channel=256, l2_norm=1e-07, patience=15, wandb=True, cache=True, log_dir='../../de_logistics/MnMs_1UNetlinear_02-03-13-52-29/', log_file_path='../../de_logistics/MnMs_1UNetlinear_02-03-13-52-29/training.log')
Epoch 1/500 [Training]:   0%|                                           | 0/188 [00:01<?, ?batch/s]
Traceback (most recent call last):
  File "/data2/lyw/deunet_mem_based/train.py", line 220, in <module>
    main(args, net)
  File "/data2/lyw/deunet_mem_based/train.py", line 68, in main
    train_acc, train_losses = train_epoch(args, net, optimizer, train_loader, device, epoch, scheduler)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data2/lyw/deunet_mem_based/train.py", line 139, in train_epoch
    train_losses, train_acc, _= process_epoch(args, net, train_loader, device, 'train', optimizer, scaler, scheduler)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data2/lyw/deunet_mem_based/train.py", line 110, in process_epoch
    total_acc += evaluator.dice_score()
                 ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Evaluator' object has no attribute 'dice_score'
